{
    'name': 'Website Searchbar for New Table/Model',
    'category': 'Website',
    'sequence': 1,
    'author': 'Kamal Aziz Adinata',
    'summary': 'Website Searchbar for New Table/Model',
    'version': '13.0.0',
    'description': "Custom Web Searchbar for new model, can search content in the new models",
    'depends': ['website', 'website_helpdesk'],
    'images': ['static/description/banner.png'],
    'data': [
        'views/header.xml',
        'security/ir.model.access.csv',
        'views/document_helpdesk_view.xml',
        'views/website_document_helpdesk_view.xml',
        'views/document_helpdesk_templates.xml',
    ],
    'active': False,
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 40.0,
    'sequence': 1,
    'currency': 'USD',
    'live_test_url': 'https://www.youtube.com/watch?v=D3bc80Ualk8',
}
