{
    'name': 'Website Searchbar for New Table/Model',
    'category': 'Website',
    'sequence': 1,
    'author': 'Kamal Aziz Adinata',
    'summary': 'Website Searchbar for New Table/Model',
    'version': '13.0.0',
    'description': "Custom Web Searchbar for new model, can search content in the new models",
    'depends': ['website', 'website_helpdesk'],
    'data': [
        'views/header.xml',
        'security/ir.model.access.csv',
        'views/document_helpdesk_view.xml',
        'views/website_document_helpdesk_view.xml',
        'views/document_helpdesk_templates.xml',
    ],
    'installable': True,
    'application': True,
    'images': ['static/description/banner.jpg'],
}
